# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\style\config_window_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConfigureDialog(object):
    def setupUi(self, ConfigureDialog):
        ConfigureDialog.setObjectName("ConfigureDialog")
        ConfigureDialog.resize(626, 486)
        ConfigureDialog.setStyleSheet(
            "QDialog{\n"
            "    color: #cfab2d;\n"
            "    background-color: #2a292e;\n"
            "    border: 3px solid #cfab2d;\n"
            "    border-radius: 10px;\n"
            "}\n"
            ""
        )
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(ConfigureDialog)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.vert_center_layout = QtWidgets.QVBoxLayout()
        self.vert_center_layout.setObjectName("vert_center_layout")
        self.vert_layout = QtWidgets.QVBoxLayout()
        self.vert_layout.setObjectName("vert_layout")
        self.setting_label = QtWidgets.QLabel(ConfigureDialog)
        self.setting_label.setStyleSheet(
            "QLabel{\n"
            "    color: #cfab2d;\n"
            "    text-align: center;\n"
            "    margin: 0 auto;\n"
            "    font-weight: bold;\n"
            "    font-size: 20px;\n"
            "    font-family: sans-serif;\n"
            "    text-transform: uppercase;\n"
            "    letter-spacing: 0.1em;\n"
            "}"
        )
        self.setting_label.setAlignment(QtCore.Qt.AlignCenter)
        self.setting_label.setObjectName("setting_label")
        self.vert_layout.addWidget(self.setting_label)
        self.buttons_photo_hor_layout = QtWidgets.QHBoxLayout()
        self.buttons_photo_hor_layout.setObjectName("buttons_photo_hor_layout")
        self.buttons_vert_layout = QtWidgets.QVBoxLayout()
        self.buttons_vert_layout.setObjectName("buttons_vert_layout")
        spacerItem = QtWidgets.QSpacerItem(
            20, 2, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.buttons_vert_layout.addItem(spacerItem)
        self.test_connection_button = QtWidgets.QPushButton(ConfigureDialog)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.test_connection_button.sizePolicy().hasHeightForWidth()
        )
        self.test_connection_button.setSizePolicy(sizePolicy)
        self.test_connection_button.setStyleSheet(
            "QPushButton{\n"
            "    color: #cfab2d;\n"
            "    background-color: #2a292e;\n"
            "    text-align: center;\n"
            "    max-width: 33em;\n"
            "    width: 12em;\n"
            "    font-size: 16px;\n"
            "    height: 3em;\n"
            "    font-weight: bold;\n"
            "    font-family: sans-serif;\n"
            "    text-transform: uppercase;\n"
            "    letter-spacing: 0.1em;\n"
            "    border: 3px solid #cfab2d;\n"
            "    border-radius: 10px;\n"
            "}\n"
            "\n"
            "QPushButton:hover{\n"
            "    color:#2a292e;\n"
            "    background-color: #cfab2d;\n"
            "}"
        )
        self.test_connection_button.setObjectName("test_connection_button")
        self.buttons_vert_layout.addWidget(self.test_connection_button)
        spacerItem1 = QtWidgets.QSpacerItem(
            20, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.buttons_vert_layout.addItem(spacerItem1)
        self.latency_info_label = QtWidgets.QLabel(ConfigureDialog)
        self.latency_info_label.setStyleSheet(
            "QLabel{\n"
            "    color: #cfab2d;\n"
            "    max-width: 33em;\n"
            "    font-size: 11px;\n"
            "    font-weight: bold;\n"
            "    font-family: sans-serif;\n"
            "    text-transform: uppercase;\n"
            "    letter-spacing: 0.1em;\n"
            "}"
        )
        self.latency_info_label.setObjectName("latency_info_label")
        self.buttons_vert_layout.addWidget(self.latency_info_label)
        self.latency_out_label = QtWidgets.QLabel(ConfigureDialog)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.latency_out_label.sizePolicy().hasHeightForWidth()
        )
        self.latency_out_label.setSizePolicy(sizePolicy)
        self.latency_out_label.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.latency_out_label.setStyleSheet(
            "*{\n"
            "    color: #cfab2d;\n"
            "    background-color: #2a292e;\n"
            "    text-align: center;\n"
            "    max-width: 33em;\n"
            "    width: 12em;\n"
            "    font-size: 16px;\n"
            "    height: 3em;\n"
            "    font-weight: bold;\n"
            "    font-family: sans-serif;\n"
            "    text-transform: uppercase;\n"
            "    letter-spacing: 0.1em;\n"
            "    border: 3px solid #cfab2d;\n"
            "    border-radius: 10px;\n"
            "    min-height: 1em;\n"
            "}"
        )
        self.latency_out_label.setText("")
        self.latency_out_label.setObjectName("latency_out_label")
        self.buttons_vert_layout.addWidget(self.latency_out_label)
        spacerItem2 = QtWidgets.QSpacerItem(
            20, 38, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.buttons_vert_layout.addItem(spacerItem2)
        self.ch_serv_info_label = QtWidgets.QLabel(ConfigureDialog)
        self.ch_serv_info_label.setStyleSheet(
            "QLabel{\n"
            "    color: #cfab2d;\n"
            "    max-width: 33em;\n"
            "    font-size: 11px;\n"
            "    font-weight: bold;\n"
            "    font-family: sans-serif;\n"
            "    text-transform: uppercase;\n"
            "    letter-spacing: 0.1em;\n"
            "}"
        )
        self.ch_serv_info_label.setObjectName("ch_serv_info_label")
        self.buttons_vert_layout.addWidget(self.ch_serv_info_label)
        self.server_box = QtWidgets.QComboBox(ConfigureDialog)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.server_box.sizePolicy().hasHeightForWidth())
        self.server_box.setSizePolicy(sizePolicy)
        self.server_box.setAutoFillBackground(False)
        self.server_box.setStyleSheet(
            "QComboBox:editable {\n"
            "    color: #cfab2d;\n"
            "    background-color: #2a292e;\n"
            "    font-weight: bold;\n"
            "    max-width: 33em;\n"
            "    width: 16em;\n"
            "    font-family: sans-serif;\n"
            "    font-size: 12px;\n"
            "    min-width: 12em;\n"
            "    letter-spacing: 0.1em;\n"
            "    opacity: 100;\n"
            "    letter-spacing: 0.1em;\n"
            "    border: 3px solid #cfab2d;\n"
            "    border-radius: 10px;\n"
            "    min-height: 3em;\n"
            "}\n"
            "QComboBox QAbstractItemView{\n"
            "    border: 2px;\n"
            "    color:#cfab2d;\n"
            "    background-color: transparent;\n"
            "}\n"
            "QComboBox QAbstractItemView:hover{\n"
            "    color:#ffffff;\n"
            "    background-color: transparent;\n"
            "}"
        )
        self.server_box.setEditable(True)
        self.server_box.setMaxVisibleItems(5)
        self.server_box.setPlaceholderText("")
        self.server_box.setFrame(True)
        self.server_box.setObjectName("server_box")
        self.server_box.addItem("")
        self.server_box.addItem("")
        self.server_box.addItem("")
        self.buttons_vert_layout.addWidget(self.server_box)
        spacerItem3 = QtWidgets.QSpacerItem(
            20, 2, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.buttons_vert_layout.addItem(spacerItem3)
        self.buttons_photo_hor_layout.addLayout(self.buttons_vert_layout)
        self.photo_label = QtWidgets.QLabel(ConfigureDialog)
        self.photo_label.setMinimumSize(QtCore.QSize(355, 355))
        self.photo_label.setMaximumSize(QtCore.QSize(16777215, 355))
        self.photo_label.setStyleSheet(
            "QLabel{\n"
            "border: 3px solid #cfab2d;\n"
            "border-radius: 13px;\n"
            "color: #cfab2d;\n"
            "text-align: center;\n"
            "font-weight: bold;\n"
            "font-size: 30px;\n"
            "font-family: sans-serif;\n"
            "text-transform: uppercase;\n"
            "letter-spacing: 0.1em;\n"
            "}"
        )
        self.photo_label.setText("")
        self.photo_label.setAlignment(QtCore.Qt.AlignCenter)
        self.photo_label.setObjectName("photo_label")
        self.buttons_photo_hor_layout.addWidget(self.photo_label)
        self.vert_layout.addLayout(self.buttons_photo_hor_layout)
        self.ch_canc_hor_layout = QtWidgets.QHBoxLayout()
        self.ch_canc_hor_layout.setObjectName("ch_canc_hor_layout")
        self.change_server_button = QtWidgets.QPushButton(ConfigureDialog)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.change_server_button.sizePolicy().hasHeightForWidth()
        )
        self.change_server_button.setSizePolicy(sizePolicy)
        self.change_server_button.setStyleSheet(
            "QPushButton{\n"
            "    color: #cfab2d;\n"
            "    background-color: #2a292e;\n"
            "    text-align: center;\n"
            "    max-width: 33em;\n"
            "    width: 12em;\n"
            "    font-size: 16px;\n"
            "    height: 3em;\n"
            "    font-weight: bold;\n"
            "    font-family: sans-serif;\n"
            "    text-transform: uppercase;\n"
            "    letter-spacing: 0.1em;\n"
            "    border: 3px solid #cfab2d;\n"
            "    border-radius: 10px;\n"
            "}\n"
            "\n"
            "QPushButton:hover{\n"
            "    color:#2a292e;\n"
            "    background-color: #cfab2d;\n"
            "}"
        )
        self.change_server_button.setObjectName("change_server_button")
        self.ch_canc_hor_layout.addWidget(self.change_server_button)
        self.exit_button = QtWidgets.QPushButton(ConfigureDialog)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exit_button.sizePolicy().hasHeightForWidth())
        self.exit_button.setSizePolicy(sizePolicy)
        self.exit_button.setStyleSheet(
            "QPushButton{\n"
            "    color: #cfab2d;\n"
            "    background-color: #2a292e;\n"
            "    text-align: center;\n"
            "    max-width: 33em;\n"
            "    width: 12em;\n"
            "    font-size: 16px;\n"
            "    height: 3em;\n"
            "    font-weight: bold;\n"
            "    font-family: sans-serif;\n"
            "    text-transform: uppercase;\n"
            "    letter-spacing: 0.1em;\n"
            "    border: 3px solid #cfab2d;\n"
            "    border-radius: 10px;\n"
            "}\n"
            "\n"
            "QPushButton:hover{\n"
            "    color:#2a292e;\n"
            "    background-color: #cfab2d;\n"
            "}"
        )
        self.exit_button.setObjectName("exit_button")
        self.ch_canc_hor_layout.addWidget(self.exit_button)
        self.vert_layout.addLayout(self.ch_canc_hor_layout)
        self.vert_center_layout.addLayout(self.vert_layout)
        self.horizontalLayout_3.addLayout(self.vert_center_layout)

        self.retranslateUi(ConfigureDialog)
        self.server_box.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ConfigureDialog)

    def retranslateUi(self, ConfigureDialog):
        _translate = QtCore.QCoreApplication.translate
        ConfigureDialog.setWindowTitle(_translate("ConfigureDialog", "Dialog"))
        self.setting_label.setText(_translate("ConfigureDialog", "SETTINGS"))
        self.test_connection_button.setText(
            _translate("ConfigureDialog", "TEST CONNECTION")
        )
        self.latency_info_label.setText(_translate("ConfigureDialog", "DELAY:"))
        self.ch_serv_info_label.setText(_translate("ConfigureDialog", "CHOOSE SERVER:"))
        self.server_box.setCurrentText(_translate("ConfigureDialog", "ubuntu"))
        self.server_box.setItemText(0, _translate("ConfigureDialog", "ubuntu"))
        self.server_box.setItemText(1, _translate("ConfigureDialog", "DESKTOP-HT34P2E"))
        self.server_box.setItemText(2, _translate("ConfigureDialog", "pc"))
        self.change_server_button.setText(
            _translate("ConfigureDialog", "CHANGE SERVER")
        )
        self.exit_button.setText(_translate("ConfigureDialog", "EXIT"))
