# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/detect_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DetectDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1269, 720)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        Dialog.setFont(font)
        Dialog.setStyleSheet(
            "QDialog{\n"
            "color: #cfab2d;\n"
            "background-color: #2a292e;\n"
            "border: 3px solid #cfab2d;\n"
            "border-radius: 10px;}\n"
            "   "
        )
        self.title_label = QtWidgets.QLabel(Dialog)
        self.title_label.setGeometry(QtCore.QRect(0, 10, 1261, 30))
        self.title_label.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.title_label.setFont(font)
        self.title_label.setStyleSheet(
            "QLabel {\n"
            "font-family: sans-serif;\n"
            "color: #cfab2d;\n"
            "font-size: 20px;\n"
            "font-weight: bold;\n"
            "}"
        )
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(10, 350, 1251, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(10, 370, 1261, 331))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.image_label_1 = QtWidgets.QLabel(self.widget)
        self.image_label_1.setMinimumSize(QtCore.QSize(150, 150))
        self.image_label_1.setMaximumSize(QtCore.QSize(150, 150))
        self.image_label_1.setStyleSheet(
            "QLabel{\n" "border: 3px solid gold;\n" "border-radius: 10px;\n" "}"
        )
        self.image_label_1.setText("")
        self.image_label_1.setObjectName("image_label_1")
        self.horizontalLayout_6.addWidget(self.image_label_1)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.pred_label_1 = QtWidgets.QLabel(self.widget)
        self.pred_label_1.setStyleSheet(
            "QLabel {\n"
            "border: 2px solid gold;\n"
            "font-family:sans-serif;\n"
            "color: white;\n"
            "font-size: 14px;\n"
            "text-align: center;\n"
            "border-radius: 10px;\n"
            "}"
        )
        self.pred_label_1.setText("")
        self.pred_label_1.setObjectName("pred_label_1")
        self.verticalLayout.addWidget(self.pred_label_1)
        self.conf_label_1 = QtWidgets.QLabel(self.widget)
        self.conf_label_1.setStyleSheet(
            "QLabel {\n"
            "border: 2px solid gold;\n"
            "font-family:sans-serif;\n"
            "color: white;\n"
            "font-size: 14px;\n"
            "text-align: center;\n"
            "border-radius: 10px;\n"
            "}"
        )
        self.conf_label_1.setText("")
        self.conf_label_1.setObjectName("conf_label_1")
        self.verticalLayout.addWidget(self.conf_label_1)
        self.sec_label_1 = QtWidgets.QLabel(self.widget)
        self.sec_label_1.setStyleSheet(
            "QLabel {\n"
            "border: 2px solid gold;\n"
            "font-family:sans-serif;\n"
            "color: white;\n"
            "font-size: 14px;\n"
            "text-align: center;\n"
            "border-radius: 10px;\n"
            "}"
        )
        self.sec_label_1.setText("")
        self.sec_label_1.setObjectName("sec_label_1")
        self.verticalLayout.addWidget(self.sec_label_1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.image_label_2 = QtWidgets.QLabel(self.widget)
        self.image_label_2.setMinimumSize(QtCore.QSize(150, 150))
        self.image_label_2.setMaximumSize(QtCore.QSize(150, 150))
        self.image_label_2.setStyleSheet(
            "QLabel{\n" "border: 3px solid gold;\n" "border-radius: 10px;\n" "}"
        )
        self.image_label_2.setText("")
        self.image_label_2.setObjectName("image_label_2")
        self.horizontalLayout_5.addWidget(self.image_label_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.pred_label_2 = QtWidgets.QLabel(self.widget)
        self.pred_label_2.setStyleSheet(
            "QLabel {\n"
            "border: 2px solid gold;\n"
            "font-family:sans-serif;\n"
            "color: white;\n"
            "font-size: 14px;\n"
            "text-align: center;\n"
            "border-radius: 10px;\n"
            "}"
        )
        self.pred_label_2.setText("")
        self.pred_label_2.setObjectName("pred_label_2")
        self.verticalLayout_2.addWidget(self.pred_label_2)
        self.conf_label_2 = QtWidgets.QLabel(self.widget)
        self.conf_label_2.setStyleSheet(
            "QLabel {\n"
            "border: 2px solid gold;\n"
            "font-family:sans-serif;\n"
            "color: white;\n"
            "font-size: 14px;\n"
            "text-align: center;\n"
            "border-radius: 10px;\n"
            "}"
        )
        self.conf_label_2.setText("")
        self.conf_label_2.setObjectName("conf_label_2")
        self.verticalLayout_2.addWidget(self.conf_label_2)
        self.sec_label_2 = QtWidgets.QLabel(self.widget)
        self.sec_label_2.setStyleSheet(
            "QLabel {\n"
            "border: 2px solid gold;\n"
            "font-family:sans-serif;\n"
            "color: white;\n"
            "font-size: 14px;\n"
            "text-align: center;\n"
            "border-radius: 10px;\n"
            "}"
        )
        self.sec_label_2.setText("")
        self.sec_label_2.setObjectName("sec_label_2")
        self.verticalLayout_2.addWidget(self.sec_label_2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.image_label_3 = QtWidgets.QLabel(self.widget)
        self.image_label_3.setMinimumSize(QtCore.QSize(150, 150))
        self.image_label_3.setMaximumSize(QtCore.QSize(150, 150))
        self.image_label_3.setStyleSheet(
            "QLabel{\n" "border: 3px solid gold;\n" "border-radius: 10px;\n" "}"
        )
        self.image_label_3.setText("")
        self.image_label_3.setObjectName("image_label_3")
        self.horizontalLayout_4.addWidget(self.image_label_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.pred_label_3 = QtWidgets.QLabel(self.widget)
        self.pred_label_3.setStyleSheet(
            "QLabel {\n"
            "border: 2px solid gold;\n"
            "font-family:sans-serif;\n"
            "color: white;\n"
            "font-size: 14px;\n"
            "text-align: center;\n"
            "border-radius: 10px;\n"
            "}"
        )
        self.pred_label_3.setText("")
        self.pred_label_3.setObjectName("pred_label_3")
        self.verticalLayout_3.addWidget(self.pred_label_3)
        self.conf_label_3 = QtWidgets.QLabel(self.widget)
        self.conf_label_3.setStyleSheet(
            "QLabel {\n"
            "border: 2px solid gold;\n"
            "font-family:sans-serif;\n"
            "color: white;\n"
            "font-size: 14px;\n"
            "text-align: center;\n"
            "border-radius: 10px;\n"
            "}"
        )
        self.conf_label_3.setText("")
        self.conf_label_3.setObjectName("conf_label_3")
        self.verticalLayout_3.addWidget(self.conf_label_3)
        self.sec_label_3 = QtWidgets.QLabel(self.widget)
        self.sec_label_3.setStyleSheet(
            "QLabel {\n"
            "border: 2px solid gold;\n"
            "font-family:sans-serif;\n"
            "color: white;\n"
            "font-size: 14px;\n"
            "text-align: center;\n"
            "border-radius: 10px;\n"
            "}"
        )
        self.sec_label_3.setText("")
        self.sec_label_3.setObjectName("sec_label_3")
        self.verticalLayout_3.addWidget(self.sec_label_3)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.image_label_4 = QtWidgets.QLabel(self.widget)
        self.image_label_4.setMinimumSize(QtCore.QSize(150, 150))
        self.image_label_4.setMaximumSize(QtCore.QSize(150, 150))
        self.image_label_4.setStyleSheet(
            "QLabel{\n" "border: 3px solid gold;\n" "border-radius: 10px;\n" "}"
        )
        self.image_label_4.setText("")
        self.image_label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.image_label_4.setObjectName("image_label_4")
        self.horizontalLayout_3.addWidget(self.image_label_4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.pred_label_4 = QtWidgets.QLabel(self.widget)
        self.pred_label_4.setStyleSheet(
            "QLabel {\n"
            "border: 2px solid gold;\n"
            "font-family:sans-serif;\n"
            "color: white;\n"
            "font-size: 14px;\n"
            "text-align: center;\n"
            "border-radius: 10px;\n"
            "}"
        )
        self.pred_label_4.setText("")
        self.pred_label_4.setObjectName("pred_label_4")
        self.verticalLayout_4.addWidget(self.pred_label_4)
        self.conf_label_4 = QtWidgets.QLabel(self.widget)
        self.conf_label_4.setStyleSheet(
            "QLabel {\n"
            "border: 2px solid gold;\n"
            "font-family:sans-serif;\n"
            "color: white;\n"
            "font-size: 14px;\n"
            "text-align: center;\n"
            "border-radius: 10px;\n"
            "}"
        )
        self.conf_label_4.setText("")
        self.conf_label_4.setObjectName("conf_label_4")
        self.verticalLayout_4.addWidget(self.conf_label_4)
        self.sec_label_4 = QtWidgets.QLabel(self.widget)
        self.sec_label_4.setStyleSheet(
            "QLabel {\n"
            "border: 2px solid gold;\n"
            "font-family:sans-serif;\n"
            "color: white;\n"
            "font-size: 14px;\n"
            "text-align: center;\n"
            "border-radius: 10px;\n"
            "}"
        )
        self.sec_label_4.setText("")
        self.sec_label_4.setObjectName("sec_label_4")
        self.verticalLayout_4.addWidget(self.sec_label_4)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.image_label_5 = QtWidgets.QLabel(self.widget)
        self.image_label_5.setMinimumSize(QtCore.QSize(150, 150))
        self.image_label_5.setMaximumSize(QtCore.QSize(150, 150))
        self.image_label_5.setStyleSheet(
            "QLabel{\n" "border: 3px solid gold;\n" "border-radius: 10px;\n" "}"
        )
        self.image_label_5.setText("")
        self.image_label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.image_label_5.setObjectName("image_label_5")
        self.horizontalLayout_2.addWidget(self.image_label_5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.pred_label_5 = QtWidgets.QLabel(self.widget)
        self.pred_label_5.setStyleSheet(
            "QLabel {\n"
            "border: 2px solid gold;\n"
            "font-family:sans-serif;\n"
            "color: white;\n"
            "font-size: 14px;\n"
            "text-align: center;\n"
            "border-radius: 10px;\n"
            "}"
        )
        self.pred_label_5.setText("")
        self.pred_label_5.setObjectName("pred_label_5")
        self.verticalLayout_5.addWidget(self.pred_label_5)
        self.conf_label_5 = QtWidgets.QLabel(self.widget)
        self.conf_label_5.setStyleSheet(
            "QLabel {\n"
            "border: 2px solid gold;\n"
            "font-family:sans-serif;\n"
            "color: white;\n"
            "font-size: 14px;\n"
            "text-align: center;\n"
            "border-radius: 10px;\n"
            "}"
        )
        self.conf_label_5.setText("")
        self.conf_label_5.setObjectName("conf_label_5")
        self.verticalLayout_5.addWidget(self.conf_label_5)
        self.sec_label_5 = QtWidgets.QLabel(self.widget)
        self.sec_label_5.setStyleSheet(
            "QLabel {\n"
            "border: 2px solid gold;\n"
            "font-family:sans-serif;\n"
            "color: white;\n"
            "font-size: 14px;\n"
            "text-align: center;\n"
            "border-radius: 10px;\n"
            "}"
        )
        self.sec_label_5.setText("")
        self.sec_label_5.setObjectName("sec_label_5")
        self.verticalLayout_5.addWidget(self.sec_label_5)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.widget1 = QtWidgets.QWidget(Dialog)
        self.widget1.setGeometry(QtCore.QRect(180, 51, 911, 302))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(150, -1, -1, -1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.delay_label = QtWidgets.QLabel(self.widget1)
        self.delay_label.setMaximumSize(QtCore.QSize(300, 40))
        self.delay_label.setStyleSheet(
            "QLabel {\n"
            "border: 2px solid gold;\n"
            "font-family:sans-serif;\n"
            "color: #cfab2d;\n"
            "font-size: 14px;\n"
            "border-radius: 10px;\n"
            "}"
        )
        self.delay_label.setText("")
        self.delay_label.setObjectName("delay_label")
        self.verticalLayout_7.addWidget(self.delay_label)
        self.conf_label = QtWidgets.QLabel(self.widget1)
        self.conf_label.setMaximumSize(QtCore.QSize(300, 40))
        self.conf_label.setStyleSheet(
            "QLabel {\n"
            "border: 2px solid gold;\n"
            "font-family:sans-serif;\n"
            "color: #cfab2d;\n"
            "font-size: 14px;\n"
            "border-radius: 10px;\n"
            "}"
        )
        self.conf_label.setText("")
        self.conf_label.setObjectName("conf_label")
        self.verticalLayout_7.addWidget(self.conf_label)
        self.pred_label = QtWidgets.QLabel(self.widget1)
        self.pred_label.setMinimumSize(QtCore.QSize(300, 40))
        self.pred_label.setMaximumSize(QtCore.QSize(300, 40))
        self.pred_label.setStyleSheet(
            "QLabel {\n"
            "border: 2px solid gold;\n"
            "font-family:sans-serif;\n"
            "color: #cfab2d;\n"
            "font-size: 14px;\n"
            "border-radius: 10px;\n"
            "}"
        )
        self.pred_label.setText("")
        self.pred_label.setObjectName("pred_label")
        self.verticalLayout_7.addWidget(self.pred_label)
        self.verticalLayout_6.addLayout(self.verticalLayout_7)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(150, -1, 150, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.detect_again_button = QtWidgets.QPushButton(self.widget1)
        self.detect_again_button.setMinimumSize(QtCore.QSize(0, 30))
        self.detect_again_button.setMaximumSize(QtCore.QSize(100, 16777215))
        self.detect_again_button.setStyleSheet(
            "QPushButton {\n"
            "border: 2px solid gold;\n"
            "font-family: sans-serif;\n"
            "color: #cfab2d;\n"
            "background-color: #2a292e;\n"
            "text-align: center;\n"
            "font-size: 12px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "border: 2px solid gold;\n"
            "font-family: sans-serif;\n"
            "color:#2a292e;\n"
            "background-color: #cfab2d;\n"
            "}\n"
            "\n"
            ""
        )
        self.detect_again_button.setObjectName("detect_again_button")
        self.horizontalLayout_7.addWidget(self.detect_again_button)
        self.back_button = QtWidgets.QPushButton(self.widget1)
        self.back_button.setMinimumSize(QtCore.QSize(0, 30))
        self.back_button.setMaximumSize(QtCore.QSize(100, 16777215))
        self.back_button.setStyleSheet(
            "QPushButton {\n"
            "border: 2px solid gold;\n"
            "font-family: sans-serif;\n"
            "color: #cfab2d;\n"
            "background-color: #2a292e;\n"
            "text-align: center;\n"
            "font-size: 12px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "border: 2px solid gold;\n"
            "font-family: sans-serif;\n"
            "color:#2a292e;\n"
            "background-color: #cfab2d;\n"
            "}"
        )
        self.back_button.setObjectName("back_button")
        self.horizontalLayout_7.addWidget(self.back_button)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8.addLayout(self.verticalLayout_6)
        self.main_image_label = QtWidgets.QLabel(self.widget1)
        self.main_image_label.setMinimumSize(QtCore.QSize(300, 300))
        self.main_image_label.setMaximumSize(QtCore.QSize(300, 300))
        self.main_image_label.setStyleSheet(
            "QLabel{\n" "border: 3px solid gold;\n" "border-radius: 10px;\n" "}"
        )
        self.main_image_label.setText("")
        self.main_image_label.setObjectName("main_image_label")
        self.horizontalLayout_8.addWidget(self.main_image_label)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.images_labels_dict = {
            1: {
                "image": self.image_label_1,
                "pred": self.pred_label_1,
                "conf": self.conf_label_1,
                "sec": self.sec_label_1,
            },
            2: {
                "image": self.image_label_2,
                "pred": self.pred_label_2,
                "conf": self.conf_label_2,
                "sec": self.sec_label_2,
            },
            3: {
                "image": self.image_label_3,
                "pred": self.pred_label_3,
                "conf": self.conf_label_3,
                "sec": self.sec_label_3,
            },
            4: {
                "image": self.image_label_4,
                "pred": self.pred_label_4,
                "conf": self.conf_label_4,
                "sec": self.sec_label_4,
            },
            5: {
                "image": self.image_label_5,
                "pred": self.pred_label_5,
                "conf": self.conf_label_5,
                "sec": self.sec_label_5,
            },
        }

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.title_label.setText(_translate("Dialog", "MASK DETECTION"))
        self.detect_again_button.setText(_translate("Dialog", "DETECT AGAIN"))
        self.back_button.setText(_translate("Dialog", "BACK"))

    def show_stats_labels(self):
        self.main_image_label.setStyleSheet(
            "QLabel{\n" "border: 3px solid gold;\n" "border-radius: 10px;\n" "}"
        )
        self.pred_label.setStyleSheet(
            "QLabel {\n"
            "border: 2px solid gold;\n"
            "font-family:sans-serif;\n"
            "color: #cfab2d;\n"
            "font-size: 14px;\n"
            "border-radius: 10px;\n"
            "}"
        )
        self.conf_label.setStyleSheet(
            "QLabel {\n"
            "border: 2px solid gold;\n"
            "font-family:sans-serif;\n"
            "color: #cfab2d;\n"
            "font-size: 14px;\n"
            "border-radius: 10px;\n"
            "}"
        )
        self.delay_label.setStyleSheet(
            "QLabel {\n"
            "border: 2px solid gold;\n"
            "font-family:sans-serif;\n"
            "color: #cfab2d;\n"
            "font-size: 14px;\n"
            "border-radius: 10px;\n"
            "}"
        )

    def set_style_image_labels(self, second):
        self.images_labels_dict[second]["image"].setStyleSheet(
            "QLabel {\n"
            "border: 2px solid gold;\n"
            "font-family:sans-serif;\n"
            "color: white;\n"
            "font-size: 14px;\n"
            "text-align: center;\n"
            "border-radius: 10px;\n"
            "}"
        )
        self.images_labels_dict[second]["conf"].setStyleSheet(
            "QLabel {\n"
            "border: 2px solid gold;\n"
            "font-family:sans-serif;\n"
            "color: white;\n"
            "font-size: 14px;\n"
            "text-align: center;\n"
            "border-radius: 10px;\n"
            "}"
        )
        self.images_labels_dict[second]["pred"].setStyleSheet(
            "QLabel {\n"
            "border: 2px solid gold;\n"
            "font-family:sans-serif;\n"
            "color: white;\n"
            "font-size: 14px;\n"
            "text-align: center;\n"
            "border-radius: 10px;\n"
            "}"
        )
        self.images_labels_dict[second]["sec"].setStyleSheet(
            "QLabel {\n"
            "border: 2px solid gold;\n"
            "font-family:sans-serif;\n"
            "color: white;\n"
            "font-size: 14px;\n"
            "text-align: center;\n"
            "border-radius: 10px;\n"
            "}"
        )
