# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\result_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ResultWindow(object):
    def setupUi(self, ResultWindow):
        ResultWindow.setObjectName("ResultWindow")
        ResultWindow.resize(589, 260)
        ResultWindow.setMinimumSize(QtCore.QSize(589, 260))
        ResultWindow.setMaximumSize(QtCore.QSize(589, 260))
        ResultWindow.setStyleSheet(
            "QWidget #centralwidget{\n"
            "    color: #cfab2d;\n"
            "    background-color: #2a292e;\n"
            "    border: 3px solid #cfab2d;\n"
            "    border-radius: 10px;\n"
            "}"
        )
        self.centralwidget = QtWidgets.QWidget(ResultWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(
            20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout.addItem(spacerItem)
        self.main_layout = QtWidgets.QVBoxLayout()
        self.main_layout.setObjectName("main_layout")
        self.result_label = QtWidgets.QLabel(self.centralwidget)
        self.result_label.setStyleSheet(
            "QLabel{\n"
            "    color: #cfab2d;\n"
            "    text-align: center;\n"
            "    font-size: 25px;\n"
            "    font-weight: bold;\n"
            "    font-family: sans-serif;\n"
            "    text-transform: uppercase;\n"
            "    letter-spacing: 0.1em;\n"
            "}\n"
            ""
        )
        self.result_label.setText("")
        self.result_label.setAlignment(QtCore.Qt.AlignCenter)
        self.result_label.setObjectName("result_label")
        self.main_layout.addWidget(self.result_label, 0, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.main_layout.addItem(spacerItem1)
        self.buttons_video_layout = QtWidgets.QHBoxLayout()
        self.buttons_video_layout.setObjectName("buttons_video_layout")
        self.buttons_layout = QtWidgets.QVBoxLayout()
        self.buttons_layout.setObjectName("buttons_layout")
        spacerItem2 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.buttons_layout.addItem(spacerItem2)
        self.button_buy_mask = QtWidgets.QPushButton(self.centralwidget)
        self.button_buy_mask.setStyleSheet(
            "QPushButton{\n"
            "    color: #cfab2d;\n"
            "    background-color: #2a292e;\n"
            "    text-align: center;\n"
            "    max-width: 33em;\n"
            "    width: 12em;\n"
            "    font-size: 16px;\n"
            "    height: 1.4em;\n"
            "    font-weight: bold;\n"
            "    font-family: sans-serif;\n"
            "    text-transform: uppercase;\n"
            "    letter-spacing: 0.1em;\n"
            "    border: 3px solid #cfab2d;\n"
            "    border-radius: 10px;\n"
            "}\n"
            "\n"
            "QPushButton:hover{\n"
            "    color:#2a292e;\n"
            "    background-color: #cfab2d;\n"
            "}"
        )
        self.button_buy_mask.setObjectName("button_buy_mask")
        self.buttons_layout.addWidget(self.button_buy_mask, 0, QtCore.Qt.AlignHCenter)
        spacerItem3 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.buttons_layout.addItem(spacerItem3)
        self.button_read_restrictions = QtWidgets.QPushButton(self.centralwidget)
        self.button_read_restrictions.setStyleSheet(
            "QPushButton{\n"
            "    color: #cfab2d;\n"
            "    background-color: #2a292e;\n"
            "    text-align: center;\n"
            "    max-width: 33em;\n"
            "    width: 12em;\n"
            "    font-size: 16px;\n"
            "    height: 1.4em;\n"
            "    font-weight: bold;\n"
            "    font-family: sans-serif;\n"
            "    text-transform: uppercase;\n"
            "    letter-spacing: 0.1em;\n"
            "    border: 3px solid #cfab2d;\n"
            "    border-radius: 10px;\n"
            "}\n"
            "\n"
            "QPushButton:hover{\n"
            "    color:#2a292e;\n"
            "    background-color: #cfab2d;\n"
            "}"
        )
        self.button_read_restrictions.setObjectName("button_read_restrictions")
        self.buttons_layout.addWidget(
            self.button_read_restrictions, 0, QtCore.Qt.AlignHCenter
        )
        spacerItem4 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.buttons_layout.addItem(spacerItem4)
        self.buttons_video_layout.addLayout(self.buttons_layout)
        self.video_widget = QVideoWidget(self.centralwidget)
        self.video_widget.setMinimumSize(QtCore.QSize(320, 176))
        self.video_widget.setMaximumSize(QtCore.QSize(320, 176))
        self.video_widget.setStyleSheet(
            "*{\n"
            "    color: #cfab2d;\n"
            "    border: 3px solid #cfab2d;\n"
            "    border-radius: 10px;\n"
            "}"
        )
        self.video_widget.setObjectName("video_widget")
        self.buttons_video_layout.addWidget(self.video_widget)
        self.main_layout.addLayout(self.buttons_video_layout)
        self.verticalLayout.addLayout(self.main_layout)
        spacerItem5 = QtWidgets.QSpacerItem(
            20, 2, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout.addItem(spacerItem5)
        ResultWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ResultWindow)
        QtCore.QMetaObject.connectSlotsByName(ResultWindow)

    def retranslateUi(self, ResultWindow):
        _translate = QtCore.QCoreApplication.translate
        ResultWindow.setWindowTitle(_translate("ResultWindow", "MainWindow"))
        self.button_buy_mask.setText(_translate("ResultWindow", "BUY MASK"))
        self.button_read_restrictions.setText(
            _translate("ResultWindow", "READ RESTRICTIONS")
        )


from PyQt5.QtMultimediaWidgets import QVideoWidget
